version: "3.9"
name: webserver

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID
      - NET_BIND_SERVICE
    ports:
      - "192.168.2.10:80:80"
      - "192.168.2.10:443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./www:/var/www:ro

